=== howmanysmall/pendant/benchmarks/configuration-files/correctly-named-pendant/.schemas/pendant-configuration.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"additionalProperties": false,
	"deprecated": false,
	"description": "A configuration for the pendant tool. This is how you can configure the tool to your liking.",
	"patternProperties": {
		"^\u005c$schema$": {
			"description": "JSON Schema meta-schema URI (editor hint)",
			"format": "any",
			"type": "string"
		}
	},
	"properties": {
		"files": {
			"additionalProperties": false,
			"properties": {
				"client": {
					"deprecated": false,
					"description": "The files to include for the client context.",
					"items": {
						"type": "string"
					},
					"readOnly": true,
					"type": "array"
				},
				"server": {
					"deprecated": false,
					"description": "The files to include for the client context.",
					"items": {
						"type": "string"
					},
					"readOnly": true,
					"type": "array"
				},
				"shared": {
					"deprecated": false,
					"description": "The files to include for the shared context.",
					"items": {
						"type": "string"
					},
					"readOnly": true,
					"type": "array"
				},
				"testing": {
					"deprecated": false,
					"description": "The files to include for the testing context. Not required.",
					"items": {
						"type": "string"
					},
					"readOnly": true,
					"type": "array"
				}
			},
			"readOnly": true,
			"required": [
				"client",
				"server",
				"shared"
			],
			"type": "object"
		},
		"knownProblematicFiles": {
			"deprecated": false,
			"description": "Files that are known to be problems. These will be ignored.",
			"items": {
				"type": "string"
			},
			"readOnly": true,
			"type": "array"
		},
		"outputFileName": {
			"default": "problematic",
			"deprecated": false,
			"description": "The name of the file to output the analysis results to. Defaults to `problematic`.",
			"type": "string"
		},
		"projectFile": {
			"default": "default.project.json",
			"deprecated": false,
			"description": "The project file to use for the pendant tool. Defaults to `default.project.json`.",
			"pattern": "^.*\\.project\\.json$",
			"type": "string"
		}
	},
	"readOnly": true,
	"required": ["files"],
	"type": "object"
}

=== howmanysmall/pendant/benchmarks/configuration-files/incorrectly-named/pendant-cli.json
{
	"$schema": "./.schemas/pendant-configuration.schema.json",
	"files": {
		"client": ["src/client/**", "src/UIFusion/**"],
		"server": ["src/server/**"],
		"shared": ["src/shared/**"],
		"testing": ["src/testing/**"]
	},
	"knownProblematicFiles": ["src/legacy/**", "src/deprecated/**"],
	"outputFileName": "problematic",
	"projectFile": "default.project.json"
}
